import { loadCuratedMarkdownQuestions } from './curatedMarkdownQuestionBank.js';

export function loadFrontendCuratedQuestions() {
  return loadCuratedMarkdownQuestions({
    bankFile: 'frontend-question-bank.md',
    idPrefix: 'frontend-curated',
    domain: 'frontend',
    domainLabel: 'Frontend',
    topicAliases: {
      'HTML FUNDAMENTALS': 'HTML Fundamentals',
      'CSS FUNDAMENTALS': 'CSS Fundamentals',
      'CSS LAYOUTS — FLEXBOX AND GRID': 'CSS Layouts - Flexbox And Grid',
      'RESPONSIVE DESIGN': 'Responsive Design',
      'JAVASCRIPT FUNDAMENTALS': 'JavaScript Fundamentals',
      'DOM MANIPULATION': 'DOM Manipulation',
      'JAVASCRIPT ADVANCED': 'JavaScript Advanced',
      'BROWSER APIS AND WEB PLATFORM': 'Browser APIs and Web Platform',
      'TYPESCRIPT': 'TypeScript',
      'REACT': 'React',
      'STATE MANAGEMENT': 'State Management',
      'ROUTING': 'Routing',
      'PERFORMANCE OPTIMIZATION': 'Performance Optimization',
      'BUILD TOOLS AND MODULE BUNDLERS': 'Build Tools and Module Bundlers',
      'TESTING': 'Testing',
      'ACCESSIBILITY (A11Y)': 'Accessibility (A11y)',
      'SECURITY IN FRONTEND': 'Security in Frontend',
      'NEXT.JS AND MODERN FRAMEWORKS': 'Next.js and Modern Frameworks',
      'PROGRESSIVE WEB APPS AND WEB APIS': 'Progressive Web Apps and Web APIs',
      'ADVANCED FRONTEND TOPICS': 'Advanced Frontend Topics',
      'INTERVIEW SCENARIOS — ADVANCED FRONTEND': 'Interview Scenarios - Advanced Frontend',
      'FILL IN THE BLANK — MIXED ADVANCED': 'Fill in the Blank - Mixed Advanced',
      'SCENARIO QUESTIONS — INTERMEDIATE': 'Scenario Questions - Intermediate',
      'MORE FILL IN THE BLANK': 'More Fill in the Blank',
      'ADDITIONAL SCENARIOS': 'Additional Scenarios',
      'MORE ADVANCED MCQ': 'More Advanced MCQ',
      'FINAL SCENARIOS': 'Final Scenarios',
      'MORE FILL IN THE BLANK — FINAL': 'More Fill in the Blank - Final',
      'ADDITIONAL ADVANCED MCQ': 'Additional Advanced MCQ',
      'FINAL SCENARIOS AND CONCEPTS': 'Final Scenarios and Concepts',
      'RAPID FIRE FILL IN THE BLANK — FINAL 75': 'Rapid Fire Fill in the Blank - Final 75',
    },
    roundTopics: {
      concept: 'Frontend Mixed Concepts',
      fill: 'Frontend Mixed Concepts',
      scenario: 'Frontend Scenarios',
      architecture: 'Frontend Architecture',
      coding: 'Frontend Coding',
      mock: 'Frontend Mock Interview',
      faang: 'Frontend FAANG',
    },
  });
}
